version: '3.6'

services:
  db:
    restart: always
    image: postgres:13-alpine
    container_name: blockscan_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Alone
      POSTGRES_PASSWORD: Alone123!*

  vault:
    image: vault:1.3.0
    restart: always
    container_name: blockscan_vault
    volumes:
      - vault_data:/vault
    command:
      - server
    ports:
      - "8220:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: '{"storage": {"file": { "path": "/vault/data" }}, "listener": {"tcp":{"address": "0.0.0.0:8200","tls_disable":"1"}}}'
      VAULT_ADDR: http://vault:8200
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    
volumes:
  vault_data: